### ISSUE TITLE
Here's the checklist for Launch (MVP!) 

### ISSUE THREAD

**Issue by ribenaberry** [anthb/envato-cm#18]
1) Elements Title card, swap out the banner
2) Tuts "hyperlink" looking item, button migrating to the right
3) Date the campaign ends, across all marketplaces and in the Ts&Cs
4) changing the item listings to say "100" instead of 280+ graphics items etc.
5) Double checking the Studio copy across marketplaces. Adding link back in
6) Collection links to updated link
the rest are cosmetic, the Elements long footer will take longer.
7) fix social shares.
8) is the GR pricing

**Comment by ribenaberry** [comment]
- [ ] 1. long banner still needs to be swapped
- [ ] 2. Tuts hyperlink done, but there is inconsistent presentation of the three columns, some have links in the titles some don't. 
- [ ] 3. Date the campaign ends, across all marketplaces and in the Ts&Cs - DONE
4. DONE
5. Double checking the Studio copy across marketplaces. Adding link back in
6. Collection links to updated link
7. fix the social share opengraph image
8. GR pricing
the rest are cosmetic, the Elements long footer will take longer.

**Comment by jordanlewiz** [comment]
Closing in favour of individual issues so we dont get confused
